project:
  type: website

website:
  title: "My Portfolio"          # 网站标题
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: homework.qmd
        text: Homework
      - href: labs.qmd
        text: Labs

format:
  html:
    theme: cosmo                 # 网站主题
    css: styles.css              # 可选的自定义 CSS
